### ISSUE TITLE
Add Github Actions to build and push to Docker hub

### ISSUE THREAD

**Issue by Ilyes512** [Ilyes512/caddy-docker#3]
Add Github Actions to build and push to Docker hub automatically:

- `latest` tags for any changes in the `master`-branch
- git tags for any specific Caddy versions (ie git tag `v2.0.0` will build and tag a image `caddy:v2.0.0-alpine`

Question: Should we use the `v` prefix for versions?

**Comment by hairyhenderson** [comment]
> Add Gitlab Actions

I think you mean GitHub Actions?

**Comment by Ilyes512** [comment]
Eeh... oeps. Yes :)

**Comment by hairyhenderson** [comment]
> Question: Should we use the `v` prefix for versions?

No - most (all?) of the official Docker images use straight version strings, and since this is intended to be official eventually it should follow suit 😉.

As far as versions, it would be good to eventually have:

- `2.0.0`, `2.0`, `2`, `latest` (all equivalent)

Also I think it would be good to have some variants in base - at least one `alpine` set of variants (`2.0.0-alpine`, `2.0-alpine`, etc...), and it'd be good to base the default on `scratch`

**Comment by Ilyes512** [comment]
Moved to https://github.com/caddyserver/caddy-docker/issues/3
